[project]
name = "diceware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "ipython>=9.7.0",
    "rich>=14.2.0",
    "tqdm>=4.67.1",
]
